### ISSUE TITLE
タグ機能について

### ISSUE THREAD

**Issue by isakashiori** [NewBeLab/NewBeLab-Rails#17]
## 概要
ユーザーがprofileにて好きなようにタグを作成できる

## 目的
ユーザーがより自分と近い価値観のメンバーを探すため

## タスク

- [x] User _tag・Tagモデルの作成
- [x] 各モデルにてアソシエーションを作成
- [x] profileモデルにタグ編集のロジック

## 質問
ER図を見るとProfileモデルにUser _Tagモデルが関連付けされていますが、タグ記入の欄はProfilesに対して行われるのか
それともIdeasに対してタグ記入に行うのか迷ったため、教えていただきたいです。

**Comment by Mariko222** [comment]
ER図見る限りではIdeasテーブルと紐づいてなさそうなので、タグ記入はProfilesに対して行われるのかなと思いました。

**Comment by eityamo** [comment]
> タグ入力欄をviewに作成
こちらはフロントエンドで実装してくれます。
> ER図見る限りではIdeasテーブルと紐づいてなさそうなので、タグ記入はProfilesに対して行われるのかなと思いました。
私の認識も同じです

**Comment by isakashiori** [comment]
お疲れ様です！
了解しました:bow: Profilesに対してタグ記入ということで了解しました:sparkles:
viewはフロントエンドでしたね....すみません、タスクから削除しました！
