### ISSUE TITLE
ユーザーのプロフィール入力情報の設定

### ISSUE THREAD

**Issue by eityamo** [NewBeLab/NewBeLab-Rails#6]
使っているエディター
どれくらいコミットできるか
どの役割をしたいか
など

**Comment by Mariko222** [comment]
### Profilesテーブルの各カラムの概要

- times_link

  - カラム内容：Mattermost（各々のTimes）のURL

  - データ型：string型

  - バリデーション：`length: { maximum: 100}`

- commitment

  - カラム内容：どれくらいの頻度コミットできるか

  - 選択肢：週１回/週２〜３回/週４〜５回/毎日

  - データ型：string型

- position

  - カラム内容：どの位置でチーム開発に関わりたいか

  - 選択肢：バックエンド/フロントエンド/レビュー/アドバイザー/希望なし

  - データ型：string型

- motivation

  - カラム内容：どれくらいの熱量でチーム開発に関わりたいか

  - 選択肢：ガチで作成したい/ゆるく楽しく作成したい/サポートしたい

  - データ型：string型

- self_introduction

  - カラム内容：自己紹介

  - データ型：text型

  - バリデーション：`length: { maximum: 100}`

- phase

  - カラム内容：自分がどのフェーズか

  - 選択肢：カリキュラム中/PF作成中/就活中/現役エンジニア

  - データ型：string型

- editor　※無償で検索上位に出てきたものだけ挙げています

  - カラム内容：使用しているエディタ

  - 選択肢：Visual Studio Code/Atom/Vim/NoEditor/Sublime Text

  - データ型：string型

- user_id

  - 外部制約、Userモデルとは１対１のアソシエーション

  - バリデーション：`presence:true`

*** 
### 確認したいこと

- `name`カラム、`avatar_image`カラムはUserモデルの方でGitHubのユーザーネーム、アイコンを取ってきてデフォルトで設定するので良いか
- `times_link`カラムは`https://chat.runteq.jp/runteq/channels`までは共通URLなようなので、関係ないURLを登録させないようにURL形式を限定しておくかどうか
- `grade`カラムは何を意味するか
- `user_id`の制約で親レコード削除時の`dependent: :destroy`はつけるかどうか

参照：[ER図](https://drive.google.com/file/d/1AA-gLPKiWfqZJrf979PXq6wuGgDU_TPJ/view)

**Comment by eityamo** [comment]
> nameカラム、avatar_imageカラムはUserモデルの方でGitHubのユーザーネーム、アイコンを取ってきてデフォルトで設定するので良いか 
デフォルトで設定しましょう、編集できる感じでいきましょう 
> times_linkカラムはhttps://chat.runteq.jp/runteq/channelsまでは共通URLなようなので、関係ないURLを登録させないようにURL形式を限定しておくかどうか
限定しましょう
> gradeカラムは何を意味するか
言葉足らずでした、何期生かです
> user_idの制約で親レコード削除時のdependent: :destroyはつけるかどうか
つけましょう
コメント
- editorはemacsが必須です

**Comment by Mariko222** [comment]
### Profilesテーブルの各カラムの概要

- times_link

  - カラム内容：Mattermost（各々のTimes）のURL

  - データ型：string型

  - バリデーション：`length: { maximum: 100}`、URL形式を限定

- commitment

  - カラム内容：どれくらいの頻度コミットできるか

  - 選択肢：週１回/週２〜３回/週４〜５回/毎日

  - データ型：string型

- position

  - カラム内容：どの位置でチーム開発に関わりたいか

  - 選択肢：バックエンド/フロントエンド/レビュー/アドバイザー/希望なし

  - データ型：string型

- motivation

  - カラム内容：どれくらいの熱量でチーム開発に関わりたいか

  - 選択肢：ガチで作成したい/ゆるく楽しく作成したい/サポートしたい

  - データ型：string型

- self_introduction

  - カラム内容：自己紹介

  - データ型：text型

  - バリデーション：`length: { maximum: 100}`

- phase

  - カラム内容：自分がどのフェーズか

  - 選択肢：カリキュラム中/PF作成中/就活中/現役エンジニア

  - データ型：string型

- grade
   - カラム内容：何期生か
   - データ型：String型

- editor　※無償で検索上位に出てきたものだけ挙げています

  - カラム内容：使用しているエディタ

  - 選択肢：Visual Studio Code/Atom/Vim/NoEditor/Sublime Text/Emacs

  - データ型：string型

- user_id

  - 外部制約、Userモデルとは１対１のアソシエーション、親レコード削除時の`dependent: :destroy`はつける

  - バリデーション：`presence:true`

*** 
### 確認したいこと
- バリデーション、データ型は上記で問題ないか
- `grade`カラムのデータ型をどうするか（選択肢か記入させるのか、どのようにユーザーに答えてもらうか分からなかったのでひとまずString型にしています）


参照：[ER図](https://drive.google.com/file/d/1AA-gLPKiWfqZJrf979PXq6wuGgDU_TPJ/view)

**Comment by eityamo** [comment]
gradeはinteger型で想定していました。
ひよこコネクトと同じ感じでセレクトボックス形式です。
